[project]
name = "pytorch-sentiment-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "datasets>=5.0.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "numpy==1.26.4",
    "torch==2.2.2",
    "torchtext==0.17.2",
    "tqdm>=4.70.1",
    "transformers==4.35.*",
]
